### ISSUE TITLE
Error initialising the generator on choosing SCSS

### ISSUE THREAD

**Issue by mkstix6** [endel/generator-modern-frontend#9]
First question after initiating the generator is preprocessor, on answering this the process falls over.
Error as follows:

```
? Which CSS preprocessor would you like to use? SCSS

events.js:85
  throw er; // Unhandled 'error' event
        ^
AssertionError: Trying to copy from a source that does not exist: /usr/local/lib/node_modules/generator-modern-frontend/app/templates/mainundefined
at EditionInterface.exports._copySingle (/usr/local/lib/node_modules/generator-modern-frontend/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:44:3)
at EditionInterface.exports.copy (/usr/local/lib/node_modules/generator-modern-frontend/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:22:17)
at module.exports.yeoman.generators.Base.extend.writing.app (/usr/local/lib/node_modules/generator-modern-frontend/app/index.js:83:15)
at /usr/local/lib/node_modules/generator-modern-frontend/node_modules/yeoman-generator/lib/base.js:409:16
at processImmediate [as _immediateCallback] (timers.js:367:17)
```

On installing the generator there were these warnings:

```
 npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
 npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
```

**Comment by rowinf** [comment]
Ran into this issue today as well.

**Comment by endel** [comment]
@mkstix6 @rowinf thanks for your report. I'd updated `sass`/`scss` recently and hadn't tested all alternatives.

Please install the last version of the generator (0.2.3), it should work now!
